{ inputs, ... }: {
  hci-effects =
    {
      lib,
      config',
      hci-effects,
      pkgs,
      inputs',
      system,
      ...
    }:
    let
      knownHostsName = "deploy.known_hosts";
      tfCfg = config'.terranix.terranixConfigurations.nixpedition;
      tfBinaryName = tfCfg.result.terraformWrapper.meta.mainProgram;

      terraformScript = pkgs.writeShellApplication {
        name = "nixpedition-apply";
        runtimeInputs = [ tfCfg.result.terraformWrapper ];

        text = /* bash */ ''
          mkdir -p ${tfCfg.workdir}
          ln -sf ${tfCfg.result.terraformConfiguration} ${tfCfg.workdir}/config.tf.json

          ${tfBinaryName} init
          ${tfBinaryName} apply -auto-approve
        '';
      };
    in
    {
      jobs = {
        deploy = {
          on.push = {
            branches = [ "main" ];
          };

          effect = hci-effects.mkEffect {
            name = "deploy";
            lock = "production";

            checkout = true;
            inputs = [
              inputs.clan-core.packages.${system}.clan-cli
              terraformScript

              pkgs.openssh
              pkgs.git
            ];

            # Envs
            NIX_CONFIG = "experimental-features = nix-command flakes pipe-operators";
            TF_INPUT = "false";
            CLAN_NO_COMMIT = "1";

            secretsMap = {
              "ssh" = "ci-ssh-keys";
              "age" = "ci-age-key";
              "git-author" = "git-author";
            };

            getStateScript = ''
              mkdir -p ~/.ssh
              getStateFile "${knownHostsName}" ~/.ssh/known_hosts
              touch ~/.ssh/known_hosts
            '';
            putStateScript = ''
              putStateFile "${knownHostsName}" ~/.ssh/known_hosts
            '';

            userSetupScript = /* bash */ ''
              writeAgeKey
              writeSSHKey
              setupGit
            '';

            effectScript = /* bash */ ''
              # Apply global Terraform configuration
              ${lib.getExe terraformScript}

              # Commit & Push secrets generated by Terraform
              git add vars/ sops/
              if ! git diff --cached --quiet; then
                git commit -m "chore(vars): sync secrets from terraform"
                git push origin HEAD:refs/heads/main
              fi

              # Deploy Nix configuration to all machines
              # clan machines update \
              #   --host-key-check accept-new
            '';
          };
        };
      };
    };
}
