{
  hci-effects =
    {
      lib,
      config,
      systemConfig,
      hci-effects,
      pkgs,
      inputs',
      ...
    }:
    let
      NIX_CONFIG = "experimental-features = nix-command flakes pipe-operators";
      tfCfg = systemConfig.terranix.terranixConfigurations.nixpedition;
      tfBinaryName = tfCfg.result.terraformWrapper.meta.mainProgram;

      terraformScript = pkgs.writeShellApplication {
        name = "nixpedition-apply";
        runtimeInputs = [ tfCfg.result.terraformWrapper ];

        text = /* bash */ ''
          mkdir -p ${tfCfg.workdir}
          ln -sf ${tfCfg.result.terraformConfiguration} ${tfCfg.workdir}/config.tf.json

          ${tfBinaryName} init
          ${tfBinaryName} apply -auto-approve
        '';
      };
    in
    {
      jobs = {
        deploy = {
          on.push = config.repo.branch == "main";

          steps = {
            default = hci-effects.mkEffect {
              name = "deploy";
              lock = "production";

              checkout = true;
              inputs = [
                inputs'.clan-core.packages.clan-cli
                terraformScript

                pkgs.openssh
                pkgs.git
              ];

              # Envs
              inherit NIX_CONFIG;
              TF_INPUT = "false";
              CLAN_NO_COMMIT = "1";

              # Secrets
              secretsMap = {
                "ssh" = "ci-ssh-keys";
                "age" = "ci-age-key";
              };

              # State
              knownHostsName = "deploy.known_hosts";

              getStateScript = ''
                mkdir -p ~/.ssh
                getStateFile "$knownHostsName" ~/.ssh/known_hosts
                touch ~/.ssh/known_hosts
              '';
              putStateScript = ''
                putStateFile "$knownHostsName" ~/.ssh/known_hosts
              '';

              userSetupScript = /* bash */ ''
                writeAgeKey
                writeSSHKey

                # Configure git commit author
                git config --global user.name "$(readSecretString "git-author" .username)"
                git config --global user.email "$(readSecretString "git-author" .email)"
                git config --global safe.directory '*'
              '';

              effectScript = /* bash */ ''
                # Apply global Terraform configuration
                ${lib.getExe terraformScript}

                # Commit & Push secrets generated by Terraform
                git add vars/ sops/
                if ! git diff --cached --quiet; then
                  git commit -m "chore(vars): sync secrets from terraform"
                  git push origin HEAD:refs/heads/main
                fi

                # Deploy Nix configuration to all machines
                clan machines update \
                  --host-key-check accept-new
              '';
            };
          };
        };
      };
    };
}
