{
  # deadnix: skip
  __findFile ? __findFile,
  ...
}:
{
  services.zitadel = {
    includes = [
      <services/zitadel/database>
      <services/zitadel/api>
      <services/zitadel/login>
      <services/zitadel/terraform>
    ];

    nixos =
      {
        pkgs,
        constants,
        ...
      }:
      let
        inherit (constants.services.zitadel) dataDir;
      in
      {
        # Create files/directories
        systemd.tmpfiles.rules = [
          "d ${dataDir} - - - - -"
          "f ${dataDir}/login-client.pat - - - - -"
          "f ${dataDir}/service-account-key.json - - - - -"
        ];

        # Root service
        systemd.targets."podman-compose-zitadel-root" = {
          unitConfig = {
            Description = "Root target generated by compose2nix.";
          };
          wantedBy = [ "multi-user.target" ];
        };

        # Networks
        systemd.services."podman-network-zitadel" = {
          path = [ pkgs.podman ];
          serviceConfig = {
            Type = "oneshot";
            RemainAfterExit = true;
            ExecStop = "podman network rm -f zitadel";
          };
          script = ''
            podman network inspect zitadel || podman network create zitadel
          '';
          partOf = [ "podman-compose-zitadel-root.target" ];
          wantedBy = [ "podman-compose-zitadel-root.target" ];
        };
      };
  };
}
